### ISSUE TITLE
[FEATURE] Add React components and pages to Storybook

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#1944]
### Description

All React components and pages need to be added to Storybook (in the `nextjs` branch)

> **Note**
> Each item listed below for component/page should be in a new Issue and PR

- [x] `components/user/UserLink.js` https://github.com/EddieHubCommunity/LinkFree/blob/nextjs/stories/components/user/UserLink.stories.js
- [x] `components/user/UserMilestone.js` https://github.com/EddieHubCommunity/LinkFree/blob/nextjs/stories/components/user/UserMilestone.stories.js
- [ ] `components/user/UserPreview.js`
- [ ] `components/navbar/NavLink.js`
- [ ] `components/navbar/Navbar.js`
- [x] `components/footer.js`
- [x] `pages/[username].js` https://github.com/EddieHubCommunity/LinkFree/blob/nextjs/stories/pages/%5Busername%5D.stories.js
- [ ] `pages/index.js` 
- [ ] `pages/popular.js` 
- [ ] `pages/search.js` 

Steps to follow...
1. Create story file in `stories/components` with the same filename as the component but add `.stories.js`
2. Import the component into the story file
3. Set the default arguments by looking at the requirements from the component
4. Run `npm run storybook` to see the added components and interact with them

### Screenshots

<img width="1671" alt="Screenshot 2022-10-11 at 13 25 41" src="https://user-images.githubusercontent.com/624760/195089266-0faa13af-ae89-4b2b-a2b0-54e222221c26.png">

**Comment by manav-06** [comment]
hi @eddiejaoude , you can assign this to me

**Comment by eddiejaoude** [comment]
> Each item listed below for component/page should be in a new Issue and PR

Please create an issue for the item in the list that you want to do and we can assign that to you @manav-06

**Comment by DeeptanshuDas** [comment]
Hi can I contribute in this project

**Comment by Prasundas99** [comment]
Hi @eddiejaoude ,
I want to contribute to:

`components/navbar/NavLink.js`

Is it open to contribute?

**Comment by FrancescoXX** [comment]
I never user storybook but I can do this live today, if you assign this to me

**Comment by eddiejaoude** [comment]
Yes @DeeptanshuDas @Prasundas99 yes, great 👍

**Comment by eddiejaoude** [comment]
@FrancescoXX that is awesome 👍 We are not assign this issue, because it is a collection of many issues, so you can pick one from the list in the issue description - there are actually many more to do, I can update the list in the issue description

**Comment by itsagift** [comment]
Hi, I can add the UserPreview component.

**Comment by itsagift** [comment]
Hi, I can add the "popular" page.

**Comment by RKC3000** [comment]
Hello @eddiejaoude ,
I want to work on pages/search.js.

**Comment by eddiejaoude** [comment]
@RKC3000 great, please create an issue and PR for that specific story 🤓

**Comment by RKC3000** [comment]
OK @eddiejaoude 

Can you clear me on one thing?

To contribute I have to follow docs/CONTRIBUITING.md

**Comment by MAX-786** [comment]
Hey, @eddiejaoude can you assign this `components/user/UserPreview.js`  issue to me? Thanks

**Comment by eddiejaoude** [comment]
@MAX-786 what is the issue number?

**Comment by MAX-786** [comment]
@eddiejaoude #2012 can you please assign it?

**Comment by eddiejaoude** [comment]
@MAX-786 the footer component has already been checked off the list

**Comment by MAX-786** [comment]
okay @eddiejaoude , is there any left where i can contrubute?

**Comment by eddiejaoude** [comment]
Yes there are @MAX-786 , you can check in the `stories` folder https://github.com/EddieHubCommunity/LinkFree/tree/nextjs/stories

**Comment by MAX-786** [comment]
thanks @eddiejaoude, I will surely do that.

**Comment by eddiejaoude** [comment]
I will close this EPIC and people can create new issues for each Story
