### ISSUE TITLE
Replace fetches from internal APIs with function calls

### ISSUE THREAD

**Issue by dan-mba** [EddieHubCommunity/LinkFree#5069]
### Description

The [Next.js documentation](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props#getserversideprops-or-api-routes) explains that fetching data from an API route from the same server is a bad idea.

This was fixed for user profiles in #4997 .

The following pages need to be updated to follow the same style:
- [x] pages/map.js - #6939 
- [x] pages/events.js - #5152 
- [x] pages/account/statistics.js - #7028 
- [x] pages/index.js - #5124 
- [x] pages/search.js - #6946

**Comment by Harrish-Selvarajah** [comment]
Hi @eddiejaoude and @dan-mba. I see that map.js, statistic.js and search.js files need to be replaced with function calls. I'm open to take this up :).

**Comment by dan-mba** [comment]
> Hi @eddiejaoude and @dan-mba. I see that map.js, statistic.js and search.js files need to be replaced with function calls. I'm open to take this up :).

@Harrish-Selvarajah Sorry I missed your comment.
Work got stalled on this issue by the migration of loading profiles from the database.
Then got combined with fixing some performance issues.
Since there is only one file left, I will handle it to get this issue closed.
Again, I apologize for not responding sooner.

**Comment by Harrish-Selvarajah** [comment]
Hey @dan-mba, No worries! 😀

**Comment by dan-mba** [comment]
All pages are migrated
